#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          {"message":"bad request"}        
  500:
    body:
      application/json:
        example:
          {"message":"internal server error"}
  